print('''***Welcome to the Game!***

The objective this time is to guess the MYSTERY WORD generated by the computer.

MECHANICS:

 1. You may insert your answer on the space provided.
 2. If you give 5 wrong answer consecutively, a hint will be given.
 3. There is a total of 3 words to be guessed in this game with 3 hints each.
 4. Once you reach the point that you were too WEAK to answer the mystery word,
    you will be given an option to reveal the correct word, or you can continue inputting words
    until you get the correct answer.
 5. After finishing all 3 rounds, you will receive a reward for playing the game. 
 
 GOOD LUCK AND HAVE FUN!!!
''')

words_dict = { 1: {'word' : 'star',
                   'hints': ['It is a very bright object.',
                             'It creates one of the most spectacular views at night when in a group.',
                             'This object is extremely massive.',
                             'It is also extremely hot.']
                    },
               2: {'word' : 'physics',
                   'hints': ['It is something very valuable.',
                             'It is a study that has been practiced for a long time.',
                             'A branch of science.',
                             'It deals with the nature of matter and energy, and their interactions.']
                    },
               3: {'word' : 'space',
                   'hints': ['It is a place..',
                             'It is an enormous place.',
                             'A place older than any humans.',
                             'It holds otherworldly sceneries.']
                    },
              }

hint_interval = 5 # number of tries before we provide a HINT


for w_id, w_info in words_dict.items():
    print(f"***MYSTERY WORD {w_id}***")
    print(f"This word has {len(w_info['word'])} letters.")
    hints = w_info['hints']
    print(f'HINT: {hints.pop(0)}')

    guess = input('Enter your guess: ')
    tries = 1

    while guess.lower() != w_info['word'] and guess.lower() != 'i am weak':
        print("Wrong, try again...")
        tries += 1

        if tries < 20 and tries % 5 == 0:
            print(f'HINT: {hints.pop(0)}')
        elif tries == 20:
            print("You may type \"I AM WEAK\" anytime to reveal the answer, or you may continue guessing until you get it.\n(Note: No more hints will be shown for this word.)")
        
        guess = input('Enter your guess: ')

    if guess.lower() == w_info['word']:
        print(f"\nGreat job! Your total guess for this round is {tries}.\n")
        if w_id != list(words_dict)[-1]:
            print("Now for the next mystery word\n")
            print("Great job! Now for the next round!")

    elif guess.lower() == 'i am weak':
        print("\nI expected as much...\n")

print('*****THAT\'S ALL FOR TODAY, THANKS FOR PLAYING*****')
