#chosen words 
word1 = "Star"
word2 = "Physics"
word3 = "Space"
#start
print("\n***Welcome to the Game!***\n")
print("The objective this time is to guess the MYSTERY WORD generated by the computer.")
print("\nMECHANICS:\n")
print("\n 1. You may insert your answer on the space provided.\n (Note that each word must start with a CAPITAL letter.)\n 2. If you give 5 wrong answer consecutively, a hint will be given.\n 3. There is a total of 3 words to be guessed in this game with 3 hints each.\n 4. Once you reach the point that you were too WEAK to answer the mystery word,\n you will be given an option to reveal the correct word, or you can continue inputtting words\n until you get the correct answer.\n 5. After finishing all 3 rounds, you will recieve a reward for playing the game. GOOD LUCK AND HAVE FUN!!!")


#QUESTION 1

print("\n***MYSTERY WORD 1***\n")
print("\nThis word has 4 letters, it is a very bright object.\n")
ans1 = input("")
tries1 = 1
if  ans1 != word1:
	while ans1 != word1:
		print("Wrong, try again...")
		tries1 += 1
		ans1 = input("")
		if tries1 == 5:
			print("\nIt creates one of the most spectacular views at night when in a group.\n")
			tries1 += 1
			ans1 = input("")
		elif tries1 == 10:
			print("\nThis object is extremely massive.\n")
			tries1 += 1
			ans1 = input("")
		elif tries1 == 15:
			print("\nIt is also extremely hot.\n")
			tries1 += 1
			ans1 = input("")
		elif tries1 == 20:
			print("You may type \"I AM WEAK\" anytime to reveal the answer, or you may continue guessing until you get it.\n(Note: No more hints will be shown for this word.)")
			tries1 += 1
			ans1 = input("")
		elif ans1 == "I AM WEAK":
			print("\nI expected as much...\n")
			break
	if ans1 == word1:
		print(f"\nGreat job! Your total guess for this round is {tries1} guesses.\n")
		tries1 += 1
		print("\nNow for the next mystery word\n")
elif ans1 == word1:
	print("Great job! Now for the next round!")
	tries1 += 1

#QUESTION 2

print("\n***MYSTERY WORD 2***\n")
print("\nThis word has 7 letters, it is something very valuable.\n")
ans2 = input("")
tries2 = 1
if ans2 == word2:
	print("Great job! Now for the next round!")
	tries2 += 1
elif  ans2 != word2:
	while ans2 != word2:
		print("Wrong, try again...")
		tries2 += 1
		ans2 = input("")
		if tries2 == 5:
			print("\nIt is a study that has been practiced for a long time.\n")
			tries2 += 1
			ans2 = input("")
		elif tries2 == 10:
			print("\nA branch of science.\n")
			tries2 += 1
			ans2 = input("")
		elif tries2 == 15:
			print("\nIt deals with the nature of matter and energy, and their interactions.\n")
			tries2 += 1
			ans2 = input("")
		elif tries2 == 20:
			print("You may type \"I AM WEAK\" anytime to reveal the answer, or you may continue guessing until you get it.\n(Note: No more hints will be shown for this word.)")
			tries2 += 1
			ans2 = input("")
		elif ans2 == "I AM WEAK":
			print("\nI expected as much...\n")
			break
	if ans2 == word2:
		print(f"\nGreat job! Your total guess for this round is {tries2} guesses.\n")
		tries2 += 1
		print("\nNow for the next mystery word\n")
elif ans2 == word2:
	print("Great job! Now for the next round!")
	tries2 += 1

	
#QUESTION 3

print("\n***MYSTERY WORD 3***\n")
print("\nThis word has 5 letters, it is a place.\n")
ans3 = input("")
tries3 = 1
if ans3 == word3:
	print("Great job! Now for the next round!")
	tries3 += 1
elif  ans3 != word3:
	while ans3 != word3:
		print("Wrong, try again...")
		tries3 += 1
		ans3 = input("")
		if tries3 == 5:
			print("\nIt is an enormous place.\n")
			tries3 += 1
			ans3 = input("")
		elif tries3 == 10:
			print("\nA place older than any humans.\n")
			tries3 += 1
			ans3= input("")
		elif tries3 == 15:
			print("\nIt holds otherworldly sceneries.\n")
			tries3 += 1
			ans3 = input("")
		elif tries3 == 20:
			print("You may type \"I AM WEAK\" anytime to reveal the answer, or you may continue guessing until you get it.\n(Note: No more hints will be shown for this word.)")
			tries3 += 1
			ans3 = input("")
		elif ans3 == "I AM WEAK":
			print("\nI expected as much...\n")
			break
	if ans3 == word3:
		print(f"\nGreat job! Your total guess for this round is {tries3} guesses.\n")
		tries3 += 1
		print("\nNow for the next mystery word\n")
elif ans3 == word3:
	print("Great job! Now for the next round!")
	tries3 += 1

print("\n*****THAT'S ALL FOR TODAY, THANKS FOR PLAYING*****\n")